Repository GSG-CF05/Open-Fashion-HHNN, pull requests merged in 2022-02, with the labels that each got.

#8 7 create file structure
  Cart-Page/Cart-Page.css
  Cart-Page/Cart-Page.html
  Products-Page/Products-Page.css
  Products-Page/Products-Page.html
  assets/show case image.png
  index.html
  style.css
Labels: approved

#11 Create Product Details Page Floder
  Product-Details-Page/Product-Details-Page.css
  Product-Details-Page/Product-Details-Page.html
Labels: waitting-review

#13 12 create main page
  .vscode/settings.json
  assets/3.png
  assets/Banner (1).png
  assets/Logo.png
  assets/Rectangle 325 (1).png
  assets/Rectangle 325 (2).png
  assets/Rectangle 325 (3).png
  assets/Rectangle 325.png
  index.html
  style.css
Labels: approved

#15 add the product details page
  Product-Details-Page/Product-Details-Page.css
  Product-Details-Page/Product-Details-Page.html
  assets/App.png
Labels: awaiting-review

#16 Create products page and upload the image
  Products-Page/Products-Page.css
  Products-Page/Products-Page.html
  assets/1.png
  assets/2.png
  assets/4.png
  assets/5.png
  assets/55.png
  assets/Logo.png
Labels: approved

#20 write readme file
  README.md
Labels: approved

#18 Create_Cart_Page
  Cart-Page/Cart-Page.css
  Cart-Page/Cart-Page.html
  assets/Frame18.png
  assets/Rectangle344.png
  assets/shopping-bag.png
Labels: approved

#22 connection
  Product-Details-Page/Product-Details-Page.html
  Products-Page/Products-Page.css
  Products-Page/Products-Page.html
  index.html
Labels: awaiting-review

#24 edit readme file and add website link
  README.md
Labels: approved
